channels:
- conda-forge
dependencies:
- python=3.13.3
- pip<=25.0.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - lightgbm==4.6.0
  - matplotlib==3.10.3
  - numpy==2.3.1
  - pandas==2.3.1
  - pyarrow==20.0.0
  - scikit-learn==1.7.0
  - scipy==1.16.0
name: mlflow-env
